-- Databricks notebook source
-- MAGIC %md
-- MAGIC
-- MAGIC # Exploration - SQL
-- MAGIC
-- MAGIC Use this scratch file for exploration of the dataset we've just loaded in `init-lab.ipynb`:
-- MAGIC
-- MAGIC * Attach the notebook to either your serverless SQL warehouse or to a serverless compute resource (alternatively, attach it to a classic compute resource).
-- MAGIC * Use the cells below to complete the questions asked in the lab exercise.
-- MAGIC
-- MAGIC Please ask a Databricks Solution Architect if you need any assistance or are stuck.